### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by Shillos** [kiwiirc/plugin-conference#19]
I cloned it to a directory under kiwiirc and tried to yarn build and it failed countless other times over and over. What am I doing wrong?

**Comment by ItsOnlyBinary** [comment]
likely trying to use an outdated yarn and/or nodejs. If updating those does not fix your errors please make a gist of your build output

**Comment by ItsOnlyBinary** [comment]
Just quickly tested this and its building fine for me. What the readme does not say though is you need to run `yarn install` before `yarn build`

**Comment by Shillos** [comment]
i did that with yarn install before and got an error 

yarn install v1.10.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error eslint@5.4.0: The engine "node" is incompatible with this module. Expected version "^6.14.0 || ^8.10.0 || >=9.10.0". Got "9.5.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

then with yarn build this came up...

root@icecast:/var/www/html/kiwiirc/plugin-conference# yarn build
yarn run v1.10.1
$ webpack
Hash: 88ad924a8d38324ad76f
Version: webpack 4.20.2
Time: 261ms
Built at: 2018-09-29 06:39:20
      Asset      Size  Chunks             Chunk Names
    main.js  5.12 KiB    main  [emitted]  main
main.js.map  3.52 KiB    main  [emitted]  main
Entrypoint main = main.js main.js.map
[./plugin.js] 1.39 KiB {main} [built] [failed] [1 error]

ERROR in ./plugin.js
Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: Couldn't find preset "@babel/preset-env" relative to directory "/var/www/html/kiwiirc/plugin-conference"
    at /var/www/html/kiwiirc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/var/www/html/kiwiirc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/var/www/html/kiwiirc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/var/www/html/kiwiirc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/var/www/html/kiwiirc/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/var/www/html/kiwiirc/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/var/www/html/kiwiirc/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/var/www/html/kiwiirc/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/var/www/html/kiwiirc/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/var/www/html/kiwiirc/node_modules/babel-loader/lib/index.js:174:20)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@icecast:/var/www/html/kiwiirc/plugin-conference#

I don't still understand why this happens although i have nodejs the latest and yarn fully updated
node --version v9.5.0
yarn -version 1.10.1

**Comment by Shillos** [comment]
i also updated eslint with npm install -g eslint but nothing helped!

**Comment by Shillos** [comment]
Ok found the colprit. The version installed on my machine was node --version v9.5.0, while i didn't have nvm installed so thought i did so i installed that and nvm install --latest--npm after that everything went shooth yarn install and then yarn build... Lesson here is nvm is a requirement in some cases and must be used for the newer update cos on ubuntu you only get the nodejs without the nvm. Case Closed! Sorry for this!
